#!/usr/bin/env node
const fetch = require("node-fetch");
const { URL } = require("url");
const fs = require("fs");

const div = "\n";

async function followRedirects(url, display = true) {
  const data = await fetch(`https://fredirect.now.sh/api/fredirect?url=${url}`)
    .then(res => res.json());
  display && console.log(JSON.stringify(data, null, 2));
  return data
}

async function fredirect(url, { out } = { out: false }) {
  try {
    if (!/^http/.test(url)) {
      url = `http://${url}`;
    }
    const { href } = new URL(url);
    const redirects = await followRedirects(href, !Boolean(out));
    out && fs.appendFileSync(`${out}.txt`, redirects.join(div) + div);
  } catch (error) {
    console.log(error);
    const errorMessage = "Please enter a valid url";
    console.log(errorMessage);
  }
}

const args = process.argv;
if (process.stdin.isTTY) {
  const { program } = require('commander');
  program
    .version('0.0.1', '-v, --version', 'Output the current version')
    .description('Check all the redirections of a URL')
    .option("-o --out <output_filename>", "Output redirections into a file")
    .arguments('<url>')
    .action(fredirect)
    .parse(args);
} else {
  const { createInterface } = require('readline');
  const { 2: out, 3: outFilename } = args;
  if (out && !outFilename) {
    console.log("Missing required <output_filename> for '-o, --out <output_filename>'");
  }
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false
  });
  rl.on('line', url => {
    fredirect(url, { out: out && outFilename });
  });
}